In [ ]:
import numpy as np      # imports the numpy package
import math             # imports the math package
import sys, os          # imports system-related packages
import time             # imports time-related packages

print(sys.version)

3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]


Problem 1:

In [ ]:
# this is a function, by the way
def PROBLEM1():
    # Try to keep your code within 80 columns which is this line you see here  >
    # If you need more space, you can use backslash \ and get more space.
    # https://docs.python.org/3/reference/lexical_analysis.html#explicit-line-joining
    
    # YOUR CODE GOES HERE

    for count in range(1,16):
      print (count)
      if count % 2 == 0:
        print("snap")
      elif count %3 == 0:
        print("crackle")
      if count % 5 == 0:
        x = 0
        while x < int(count):
         print("pop")
         x+=1

    # no need to return anything
    return None

# DO NOT MODIFY
PROBLEM1()

1
2
snap
3
crackle
4
snap
5
pop
pop
pop
pop
pop
6
snap
7
8
snap
9
crackle
10
snap
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
11
12
snap
13
14
snap
15
crackle
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop


Problem 2:

In [ ]:
# input_list is an argument to the function, you can use it.
def PROBLEM2(input_list):
    # YOUR CODE GOES HERE
    temp =[]
    shortlist = []
    for x in input_list:
      if len(x) > 5:
        temp.append(len(x))
      else:
        shortlist.append(x)

    avg = (sum(temp) / len(temp))



    # you can return multiple values in python!
    return avg, shortlist

# DO NOT MODIFY
ex = ["hello", "this", "is", "example", "demonstrating", "problem", "statement"]
print(PROBLEM2(ex))

(9.0, ['hello', 'this', 'is'])


Problem 3:

In [ ]:


def PROBLEM3(input_matrix):
    # YOUR CODE GOES HERE
    
    ans = np.array(input_matrix[:,3::2][::2][:4][:, :-1])
    

    output_matrix = ans


    return output_matrix

# DO NOT MODIFY
np.random.seed(3251)
example = np.random.randint(0, 10, (10,10))
print(example)
print(PROBLEM3(example))

[[5 3 0 3 6 9 3 2 0 6]
 [0 6 8 3 5 1 8 2 9 8]
 [5 3 3 9 0 4 8 6 3 9]
 [6 0 5 2 1 5 2 4 9 1]
 [6 7 3 6 1 0 1 4 4 9]
 [5 8 0 1 7 3 1 1 8 7]
 [0 8 7 2 5 3 8 9 6 5]
 [6 5 2 0 0 1 7 7 3 0]
 [8 0 0 3 6 5 3 8 0 8]
 [1 2 6 2 7 3 7 3 2 7]]
[[3 9 2]
 [9 4 6]
 [6 0 4]
 [2 3 9]]


Problem 4:

In [ ]:
A = np.array([[-1, 0, 2],
             [0, 1, 4]])
B = np.array([[-2],
             [1]])
C = np.array([[3, 1], 
              [0, 0],
              [-2, -1]])
D = np.array([[5, -3]])
E = np.array([[-4, 2]])

def PROBLEM4(A, B, C, D, E):
    # YOUR CODE GOES HERE
    
    
    part1 = (np.dot(A.transpose(), B))
    part2 = (np.dot(C, (np.transpose(D + E))))
    result = (np.vdot(part1, part2))

    return result

# DO NOT MODIFY
print(PROBLEM4(A, B, C, D, E))

4


Problem 5:

In [ ]:
def P5VER1(A, B, x, y):
    # (a) Implement (A + B)(x + y) here.
    # YOUR CODE GOES HERE
    answer = ((A+B) * (x + y))


    return None

def P5VER2(A, B, x, y):
    # (a) Implement Ax + Ay + Bx + By here.
    # YOUR CODE GOES HERE
    answer2 = A*x + A*y + B*x + B*y


    return None

# DO NOT MODIFY
A = np.random.rand(1000, 2000)
B = np.random.rand(1000, 2000)
x = np.random.rand(1, 2000)
y = np.random.rand(1, 2000)

start = time.time()
P5VER1(A, B, x, y)
end = time.time()
print("Version 1 finished in:", end-start, "seconds.")

start = time.time()
P5VER2(A, B, x, y)
end = time.time()
print("Version 2 finished in:", end-start, "seconds.")

Version 1 finished in: 0.016765832901000977 seconds.
Version 2 finished in: 0.025791406631469727 seconds.


Problem 6:

**(a):** edit this text cell and write out your system of equations below. $\LaTeX$ can be used by placing each equation between dollar signs.

$y = 1$ \\
$w - 2y  = 0$ \\
$w - z = 0$ \\
$2x-3y -2z = 0$ \\

$w$FeS + $x$O$_2$ $\rightarrow$ $y$Fe$_2$O$_3$ + $z$SO$_2$


**Given:** y = 1

In [ ]:
# (b)
# Define your matrix representation here as a numpy array:

A = np.array([[0, 0, 1, 0],
              [1, 0, -2, 0],
              [1, 0, 0, -1],
              [0, 2, -3, -2]])

b = np.array([1, 0, 0, 0])


In [ ]:
# (c)

def PROBLEM6(A, b):
    # Use the numpy function you found to solve the system of linear equations.
    # YOUR CODE GOES HERE
    coeffs = np.linalg.solve(A,b)*2


    return coeffs

# DO NOT MODIFY
print(PROBLEM6(A, b))


[4. 7. 2. 4.]


**(d)** write your final, balanced chemical equation (with integers) below.

$4$FeS + $7$O$_2$ $\rightarrow$ $2$Fe$_2$O$_3$ + $4$SO$_2$


In [ ]:
def is_even_num(l):
  enum = []
  for n in l:
    if n % 2 == 0:
      enum.append(n)
  return enum

print(is_even_num([1, 2, 3, 4, 5, 6, 7, 8, 9]))


[2, 4, 6, 8]
